# action.yml
name: 'Analyse your HTTP response headers'
description: 'Quickly and easily assess the security of your HTTP response headers'
branding:
  icon: 'check-circle'  
  color: 'gray-dark'
inputs:
  url:
    description: 'URL to analyse'
    required: true
  followRedirects:
    description: 'Whether or not to follow redirects when analyzing the URL'
    required: false
  grade:
    description: 'The desired security grade of your HTTP response headers'
    required: true
outputs:
  rating:
    description: 'The security rating of your HTTP response headers'
  supportedTLS:
    description: 'List of supported TLS protocols'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
    - ${{ inputs.grade }}
    - ${{ inputs.followRedirects }}
